public with sharing class ClassOne 
{
    public ClassOne()
    {
         System.debug('ClassOne');
         //This method is add.
          //This method is add.
           //This method is add.
    }
    
    public void myMethod()
    {
         Integer ra=9;
        Integer r2=10;  
    }
    
    public void unitTestMethod()
    {
        //sdfsfse//sfe
    }
    public void errorCode(){
    for (Integer i = 0; i < 10; i++){
        Account a = new Account();
        insert a;
    }
    }
    
}